### ISSUE TITLE
Test dengan module golang yang lain

### ISSUE THREAD

**Issue by ReiiSky** [musobarlab/go-protobuf-demo#1]
Coba menggunakan module (jsoniter)[https://github.com/json-iterator/go]
untuk parser json nya.

ini yang saya hasilkan
soal memory jelas json yang menang telak hehe.

BenchmarkSerializeProductToProto-4                     1743688               687 ns/op
BenchmarkSerializeProductToJSON-4                    1572930               752 ns/op
BenchmarkDeserializeProductFromProto-4            1374864               867 ns/op
BenchmarkDeserializeProductFromJSON-4           1231454               975 ns/op

**Comment by wuriyanto48** [comment]
@Satssuki  mohon maaf, **bisa membaca hasil benchmark diatas tidak**?, ini saya jelaskan ya, hehe.
`BenchmarkSerializeProductToProto-4 1743688 687 ns/op` => artinya `Protocol buffer` bisa melakukan `1743688` hanya dengan `687 nano second`  `per operation`,
sedangkan `json iter` `BenchmarkSerializeProductToJSON-4 1572930 752 ns/op` hanya bisa melakukan `1572930` operation dengan waktu `752 nano second` `per operation`. **Itu artinya `json-iterator` lebih lama**. 

`protocol buffer` = 687 nano second/ eksekusi
`json-iterator` = 752 nano second/ eksekusi

terlihat json-iterator lebih lama

**Comment by ReiiSky** [comment]
Saya ga bicara soal performa, tapi soal memory mas haha.
tetap saja ya proto lebih cepat, terima kasih.
Mungkin saya kurang bisa menghighlight tentang penjelasan saya.
